FROM node:22.18.0-alpine3.22

WORKDIR /app

ENV HOST=0.0.0.0 \
    PORT=8080 \
    CHOKIDAR_USEPOLLING=true \
    WATCHPACK_POLLING=true \
    WDS_SOCKET_PORT=0

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

EXPOSE 8080

CMD ["yarn", "serve", "--host", "0.0.0.0", "--port", "8080"]
